//nolint:forcetypeassert // Resource schema guarantees value types retrieved from Terraform state.
package provider

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	log "log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/taliesins/terraform-provider-hyperv/api"
)

const (
	ReadIsoImageTimeout   = 1 * time.Minute
	CreateIsoImageTimeout = 5 * time.Minute
	UpdateIsoImageTimeout = 5 * time.Minute
	DeleteIsoImageTimeout = 1 * time.Minute
)

func resourceHyperVIsoImage() *schema.Resource {
	return &schema.Resource{
		// Compute hashes for local source files during diff so changes to the
		// local file contents are detected (when the corresponding hash
		// attribute has not been provided by the user).
		CustomizeDiff: func(ctx context.Context, d *schema.ResourceDiff, meta interface{}) error {
			computeIfMissing := func(sourceKey, hashKey string) error {
				v, ok := d.GetOk(sourceKey)
				if !ok {
					return nil
				}
				sourcePath := v.(string)
				if sourcePath == "" {
					return nil
				}

				// Only attempt to compute hashes for local files that exist on disk.
				// Skip urls (http://, https://, file:// etc.)
				if strings.Contains(sourcePath, "://") || strings.HasPrefix(strings.ToLower(sourcePath), "http") {
					return nil
				}

				// Expand environment variables and ~ if present via filepath (best-effort)
				expanded := os.ExpandEnv(sourcePath)
				// Do not attempt to resolve ~; leave to user if needed.

				fi, statErr := os.Stat(expanded)
				if os.IsNotExist(statErr) {
					// file not present locally; nothing to compute
					return nil
				}

				if statErr != nil {
					return statErr
				}

				if fi.IsDir() {
					// directory path; nothing to compute
					return nil
				}

				h, err := computeFileSHA256(expanded)
				if err != nil {
					return err
				}

				// If a hash was already committed during the plan phase
				// (d.GetOk returns ok=true when old != new, i.e. the planned
				// value differs from prior state) and the freshly-computed
				// hash now differs from that planned value, do NOT override
				// it.  CustomizeDiff is called a second time during apply's
				// final-plan check, and the source file may have been
				// regenerated by another resource in the meantime.
				// Preserving the planned hash avoids the
				// "Provider produced inconsistent final plan" error.
				if existingHash, ok := d.GetOk(hashKey); ok {
					if existing := existingHash.(string); existing != "" && existing != h {
						return nil
					}

					if err := d.SetNew(hashKey, h); err != nil {
						return err
					}

					return nil
				}

				// For new resources we intentionally avoid materializing a
				// concrete hash in the plan. This prevents a mutable build
				// artifact (for example a zip created by another resource in the
				// same apply) from becoming a stable planned value that can drift
				// before apply. The hash is populated into state during Create.
				if d.Id() == "" {
					return nil
				}

				if err := d.SetNew(hashKey, h); err != nil {
					return err
				}

				return nil
			}

			// compute for iso, zip and boot
			if err := computeIfMissing("source_iso_file_path", "source_iso_file_path_hash"); err != nil {
				return err
			}
			if err := computeIfMissing("source_zip_file_path", "source_zip_file_path_hash"); err != nil {
				return err
			}
			if err := computeIfMissing("source_boot_file_path", "source_boot_file_path_hash"); err != nil {
				return err
			}

			return nil
		},
		Description: "This resource allows you to manage ISOs.",
		Timeouts: &schema.ResourceTimeout{
			Read:   schema.DefaultTimeout(ReadIsoImageTimeout),
			Create: schema.DefaultTimeout(CreateIsoImageTimeout),
			Update: schema.DefaultTimeout(UpdateIsoImageTimeout),
			Delete: schema.DefaultTimeout(DeleteIsoImageTimeout),
		},
		CreateContext: resourceHyperVIsoImageCreate,
		ReadContext:   resourceHyperVIsoImageRead,
		UpdateContext: resourceHyperVIsoImageUpdate,
		DeleteContext: resourceHyperVIsoImageDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{
			"source_iso_file_path": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				StateFunc:   PathStateFunc,
				Description: "Local iso file path.",
				ConflictsWith: []string{
					"source_zip_file_path",
					"source_zip_file_path_hash",
					"source_boot_file_path",
					"source_boot_file_path_hash",
				},
			},
			"source_iso_file_path_hash": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Hash of local iso file.",
				ConflictsWith: []string{
					"source_zip_file_path",
					"source_zip_file_path_hash",
					"source_boot_file_path",
					"source_boot_file_path_hash",
				},
			},
			"source_zip_file_path": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				StateFunc:   PathStateFunc,
				Description: "Local zip file path.",
				ConflictsWith: []string{
					"source_iso_file_path",
					"source_iso_file_path_hash",
				},
			},
			"source_zip_file_path_hash": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Hash of local zip file.",
				ConflictsWith: []string{
					"source_iso_file_path",
					"source_iso_file_path_hash",
				},
			},
			"source_boot_file_path": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				StateFunc:   PathStateFunc,
				Description: "Local boot file path.",
				ConflictsWith: []string{
					"source_iso_file_path",
					"source_iso_file_path_hash",
				},
			},
			"source_boot_file_path_hash": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Hash of local boot file.",
				ConflictsWith: []string{
					"source_iso_file_path",
					"source_iso_file_path_hash",
				},
			},
			"destination_iso_file_path": {
				Type:        schema.TypeString,
				Required:    true,
				StateFunc:   PathStateFunc,
				Description: "Remote iso file path.",
				ForceNew:    true,
			},
			"destination_zip_file_path": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				StateFunc:   PathStateFunc,
				Description: "Remote zip file path. This defaults to `$env:temp\\{filename(source_zip_file_path)}`",
			},
			"destination_boot_file_path": {
				Type:        schema.TypeString,
				Optional:    true,
				Default:     "",
				StateFunc:   PathStateFunc,
				Description: "Remote boot file path. This defaults to `$env:temp\\{filename(source_boot_file_path)}`",
			},
			"iso_media_type": {
				Type:             schema.TypeString,
				Optional:         true,
				Default:          api.IsoMediaType_name[api.IsoMediaType_DVDPLUSRW_DUALLAYER],
				ValidateDiagFunc: StringKeyInMap(api.IsoMediaType_value, false),
				Description:      "Media type for iso. Valid values to use are `unknown`, `cdrom`, `cdr`, `cdrw`, `dvdrom`, `dvdram`, `dvdplusr`, `dvdplusrw`, `dvdplusr_duallayer`, `dvddashr`, `dvddashrw`, `dvddashr_duallayer`, `disk`, `dvdplusrw_duallayer`, `hddvdrom`, `hddvdr`, `hddvdram`, `bdrom`, `bdr`, `bdre`.",
			},
			"iso_file_system_type": {
				Type:             schema.TypeString,
				Optional:         true,
				Default:          api.IsoFileSystemType_name[api.IsoFileSystemType_Unknown],
				ValidateDiagFunc: StringKeyInMap(api.IsoFileSystemType_value, false),
				Description:      "File system type for iso. Valid values to use are `none`, `iso9660`, `joliet`, `iso9660|joliet`, `udf`, `joliet|udf`, `iso9660|joliet|udf`, `unknown`.",
			},
			"volume_name": {
				Type:             schema.TypeString,
				Optional:         true,
				Default:          "UNTITLED",
				ValidateDiagFunc: AllowedIsoVolumeName(),
				Description:      "Volume name for iso. Must be 15 characters or less. Characters must be `A` through `Z`, `0` through `9` or `_` (underscore)",
			},
			"resolve_destination_iso_file_path": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The remote iso file path that was used.",
			},
			"resolve_destination_zip_file_path": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The remote zip file path that was used.",
			},
			"resolve_destination_boot_file_path": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The remote boot file path that was used.",
			},
			"keep_on_destroy": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				Description: "If set to true, the ISO file (and associated uploaded files) will not be deleted from the Hyper-V host when the resource is destroyed.",
			},
		},
	}
}

// computeFileSHA256 computes the SHA256 hex digest of a local file.
func computeFileSHA256(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

// resolveLocalFileSHA256 computes the SHA256 hex digest for a local file path when the
// path points to an existing regular file on disk.
func resolveLocalFileSHA256(sourcePath string) (string, bool, error) {
	if sourcePath == "" {
		return "", false, nil
	}

	// Skip urls (http://, https://, file:// etc.)
	if strings.Contains(sourcePath, "://") || strings.HasPrefix(strings.ToLower(sourcePath), "http") {
		return "", false, nil
	}

	// Expand environment variables and ~ if present via filepath (best-effort)
	expanded := os.ExpandEnv(sourcePath)
	// Do not attempt to resolve ~; leave to user if needed.

	fi, statErr := os.Stat(expanded)
	if os.IsNotExist(statErr) {
		// file not present locally; nothing to compute
		return "", false, nil
	}

	if statErr != nil {
		return "", false, statErr
	}

	if fi.IsDir() {
		// directory path; nothing to compute
		return "", false, nil
	}

	h, err := computeFileSHA256(expanded)
	if err != nil {
		return "", false, err
	}

	return h, true, nil
}

func ensureLocalSourceFileHashState(d *schema.ResourceData, sourceKey, hashKey string) error {
	sourcePath := d.Get(sourceKey).(string)
	if sourcePath == "" {
		return nil
	}

	if existingHash := d.Get(hashKey).(string); existingHash != "" {
		return nil
	}

	hash, ok, err := resolveLocalFileSHA256(sourcePath)
	if err != nil || !ok {
		return err
	}

	if err := d.Set(hashKey, hash); err != nil {
		return err
	}

	return nil
}

func winPath(path string) string {
	if len(path) == 0 {
		return path
	}

	if strings.Contains(path, " ") {
		path = fmt.Sprintf("'%s'", strings.Trim(path, "'\""))
	}

	return strings.ReplaceAll(path, "/", "\\")
}

var windowsDriveRootPattern = regexp.MustCompile(`(?i)^([a-z]:)`) // e.g. C: or V:

func destinationDriveRoot(path string) string {
	trimmed := strings.TrimSpace(strings.Trim(path, "'\""))
	if trimmed == "" {
		return ""
	}

	if strings.HasPrefix(strings.ToLower(trimmed), "$env:") || strings.HasPrefix(trimmed, "\\") {
		return ""
	}

	normalized := strings.ReplaceAll(trimmed, "/", "\\")
	matches := windowsDriveRootPattern.FindStringSubmatch(normalized)
	if len(matches) < 2 {
		return ""
	}

	return strings.ToUpper(matches[1]) + "\\"
}

type destinationDirectoryChecker interface {
	RemoteDirectoryExists(ctx context.Context, path string) (exists bool, err error)
}

// validateDestinationDriveExists validates only concrete drive-qualified paths (e.g. C:\foo).
//
// Paths that still contain environment expressions (for example $env:TEMP\foo) are intentionally
// skipped here because those values are host-resolved at execution time and cannot be reliably
// pre-validated from provider-side string parsing.
func validateDestinationDriveExists(ctx context.Context, c destinationDirectoryChecker, destinationPath string) error {
	driveRoot := destinationDriveRoot(destinationPath)
	if driveRoot == "" {
		return nil
	}

	exists, err := c.RemoteDirectoryExists(ctx, driveRoot)
	if err != nil {
		return fmt.Errorf("failed to validate destination drive %q for path %q: %w", strings.TrimSuffix(driveRoot, "\\"), destinationPath, err)
	}

	if !exists {
		return fmt.Errorf("destination drive %q does not exist on remote host for path %q", strings.TrimSuffix(driveRoot, "\\"), destinationPath)
	}

	return nil
}

func ensureFileStateCreate(ctx context.Context, d *schema.ResourceData, c api.Client, name string) (string, error) {
	sourceFilePathKey := fmt.Sprintf("source_%s_file_path", name)
	destinationFilePathKey := fmt.Sprintf("destination_%s_file_path", name)

	sourceFilePath := (d.Get(sourceFilePathKey)).(string)
	destinationFilePath := (d.Get(destinationFilePathKey)).(string)

	resolveDestinationFilePath := destinationFilePath
	if sourceFilePath != "" && resolveDestinationFilePath == "" {
		resolveDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
	}

	if resolveDestinationFilePath != "" {
		// Validate drive existence only after destination resolution. If the path still uses
		// an environment expression ($env:*), validation is intentionally skipped by
		// validateDestinationDriveExists.
		if err := validateDestinationDriveExists(ctx, c, resolveDestinationFilePath); err != nil {
			return "", err
		}

		log.Printf("[INFO][iso-image][create] check if file exists: %#v", resolveDestinationFilePath)
		resolveDestinationFilePathExists, err := c.RemoteFileExists(ctx, resolveDestinationFilePath)
		if err != nil {
			return "", fmt.Errorf("checking for existing %s: %+v", resolveDestinationFilePath, err)
		}
		if resolveDestinationFilePathExists {
			// Check if we can adopt the existing file
			sourceFilePathHashKey := fmt.Sprintf("source_%s_file_path_hash", name)
			sourceFilePathHash := d.Get(sourceFilePathHashKey).(string)

			if sourceFilePathHash != "" {
				log.Printf("[INFO][iso-image][create] file exists, checking hash for adoption: %s", resolveDestinationFilePath)
				remoteHash, err := c.RemoteFileHash(ctx, resolveDestinationFilePath)
				if err == nil {
					remoteHash = strings.ToLower(strings.TrimSpace(remoteHash))
					expectedHash := strings.ToLower(strings.TrimSpace(sourceFilePathHash))

					if remoteHash == expectedHash {
						log.Printf("[INFO][iso-image][create] remote file hash matches expected hash - adopting existing file: %s", resolveDestinationFilePath)
						return resolveDestinationFilePath, nil
					} else {
						log.Printf("[WARN][iso-image][create] remote file hash mismatch (expected %s, got %s) - cannot adopt existing file", expectedHash, remoteHash)
					}
				} else {
					log.Printf("[WARN][iso-image][create] failed to compute remote hash: %v - cannot adopt existing file", err)
				}
			}

			return "", fmt.Errorf("A resource with the ID %q already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for %q for more information.\n terraform import %s.<resource name> %s", resolveDestinationFilePath, "remote_iso", "remote_iso", resolveDestinationFilePath)
		}

		if sourceFilePath != "" {
			err = c.RemoteFileUpload(ctx, sourceFilePath, resolveDestinationFilePath)
			if err != nil {
				return resolveDestinationFilePath, err
			}
		}
	}

	// if d.IsNewResource() {
	// }

	return resolveDestinationFilePath, nil
}

func resourceHyperVIsoImageCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Printf("[INFO][iso-image][create] creating remote iso: %#v", d)
	c := meta.(api.Client)

	if err := ensureLocalSourceFileHashState(d, "source_iso_file_path", "source_iso_file_path_hash"); err != nil {
		return diag.FromErr(err)
	}
	if err := ensureLocalSourceFileHashState(d, "source_zip_file_path", "source_zip_file_path_hash"); err != nil {
		return diag.FromErr(err)
	}
	if err := ensureLocalSourceFileHashState(d, "source_boot_file_path", "source_boot_file_path_hash"); err != nil {
		return diag.FromErr(err)
	}

	sourceIsoFilePath := (d.Get("source_iso_file_path")).(string)
	sourceIsoFilePathHash := (d.Get("source_iso_file_path_hash")).(string)
	sourceZipFilePath := (d.Get("source_zip_file_path")).(string)
	sourceZipFilePathHash := (d.Get("source_zip_file_path_hash")).(string)
	sourceBootFilePath := (d.Get("source_boot_file_path")).(string)
	sourceBootFilePathHash := (d.Get("source_boot_file_path_hash")).(string)
	destinationIsoFilePath := (d.Get("destination_iso_file_path")).(string)
	destinationZipFilePath := (d.Get("destination_zip_file_path")).(string)
	destinationBootFilePath := (d.Get("destination_boot_file_path")).(string)
	media := api.ToIsoMediaType((d.Get("iso_media_type")).(string))
	fileSystem := api.ToIsoFileSystemType((d.Get("iso_file_system_type")).(string))
	volumeName := (d.Get("volume_name")).(string)

	if destinationIsoFilePath == "" {
		return diag.Errorf("[ERROR][iso-image][create] path argument is required")
	}

	resolveDestinationIsoFilePath, err := ensureFileStateCreate(ctx, d, c, "iso")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_iso_file_path", resolveDestinationIsoFilePath); err != nil {
		return diag.FromErr(err)
	}

	resolveDestinationZipFilePath, err := ensureFileStateCreate(ctx, d, c, "zip")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_zip_file_path", resolveDestinationZipFilePath); err != nil {
		return diag.FromErr(err)
	}

	resolveDestinationBootFilePath, err := ensureFileStateCreate(ctx, d, c, "boot")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_boot_file_path", resolveDestinationBootFilePath); err != nil {
		return diag.FromErr(err)
	}

	err = c.CreateOrUpdateIsoImage(ctx, sourceIsoFilePath, sourceIsoFilePathHash, sourceZipFilePath, sourceZipFilePathHash, sourceBootFilePath, sourceBootFilePathHash, destinationIsoFilePath, destinationZipFilePath, destinationBootFilePath, media, fileSystem, volumeName, resolveDestinationIsoFilePath, resolveDestinationZipFilePath, resolveDestinationBootFilePath)

	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(destinationIsoFilePath)
	log.Printf("[INFO][iso-image][create] created remote iso: %#v", d)

	return resourceHyperVIsoImageRead(ctx, d, meta)
}

func resourceHyperVIsoImageRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	log.Printf("[INFO][iso-image][read] reading remote iso: %#v", d)
	c := meta.(api.Client)

	destinationIsoFilePath := d.Id()

	// Check if ISO file still exists on remote host
	log.Printf("[INFO][iso-image][read] checking if ISO file exists: %s", destinationIsoFilePath)
	exists, err := c.RemoteFileExists(ctx, destinationIsoFilePath)
	if err != nil {
		return diag.FromErr(fmt.Errorf("error checking if ISO file exists: %w", err))
	}

	if !exists {
		// ISO was deleted externally - remove from state
		log.Printf("[WARN][iso-image][read] ISO file not found on remote: %s - removing from state", destinationIsoFilePath)
		d.SetId("")
		return nil
	}

	log.Printf("[INFO][iso-image][read] ISO file exists: %s", destinationIsoFilePath)

	// Verify the ISO file hash matches what we expect (drift detection)
	// This detects if someone modified the ISO file externally
	sourceIsoFilePathHash := d.Get("source_iso_file_path_hash").(string)
	if sourceIsoFilePathHash != "" {
		log.Printf("[INFO][iso-image][read] computing remote file hash for drift detection")
		remoteHash, err := c.RemoteFileHash(ctx, destinationIsoFilePath)
		if err != nil {
			log.Printf("[WARN][iso-image][read] failed to compute remote hash: %v - skipping drift check", err)
		} else {
			// Normalize hashes for comparison (both lowercase, no spaces)
			remoteHash = strings.ToLower(strings.TrimSpace(remoteHash))
			expectedHash := strings.ToLower(strings.TrimSpace(sourceIsoFilePathHash))

			if remoteHash != expectedHash {
				log.Printf("[WARN][iso-image][read] ISO file hash mismatch - remote drift detected! expected: %s, got: %s", expectedHash, remoteHash)

				// Treat the resource as missing so Terraform will recreate it on the next plan/apply.
				d.SetId("")
				return nil
			} else {
				log.Printf("[INFO][iso-image][read] ISO file hash matches - no drift")
			}
		}
	}

	// All configuration fields are maintained from Terraform state
	// Hash-based drift detection above handles external file modifications
	// The existence check above handles the case where the ISO is deleted externally

	return nil
}

func ensureFileStateUpdate(ctx context.Context, d *schema.ResourceData, c api.Client, name string) (string, bool, error) {
	sourceFilePathKey := fmt.Sprintf("source_%s_file_path", name)
	sourceFilePathHashKey := fmt.Sprintf("source_%s_file_path_hash", name)
	destinationFilePathKey := fmt.Sprintf("destination_%s_file_path", name)

	sourceFilePath := (d.Get(sourceFilePathKey)).(string)
	destinationFilePath := (d.Get(destinationFilePathKey)).(string)

	switch {
	case d.HasChange(sourceFilePathKey):
		o, n := d.GetChange(sourceFilePathKey)
		oldSourceFilePath := o.(string)
		newSourceFilePath := n.(string)

		oldDestinationFilePath := ""
		if d.HasChange(destinationFilePathKey) {
			od, _ := d.GetChange(destinationFilePathKey)
			oldDestinationFilePath = od.(string)
		} else {
			oldDestinationFilePath = destinationFilePath
		}
		resolveOldDestinationFilePath := oldDestinationFilePath
		if resolveOldDestinationFilePath == "" {
			resolveOldDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(oldSourceFilePath)))
		}

		newDestinationFilePath := ""
		if d.HasChange(destinationFilePathKey) {
			_, nd := d.GetChange(destinationFilePathKey)
			newDestinationFilePath = nd.(string)
		} else {
			newDestinationFilePath = destinationFilePath
		}
		resolveNewDestinationFilePath := newDestinationFilePath
		if resolveNewDestinationFilePath == "" {
			resolveNewDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(newSourceFilePath)))
		}

		switch {
		case newSourceFilePath == "":
			// must delete the old filename as we have removed the source one
			if err := validateDestinationDriveExists(ctx, c, resolveOldDestinationFilePath); err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			err := c.RemoteFileDelete(ctx, resolveOldDestinationFilePath)
			return resolveNewDestinationFilePath, true, err
		case oldSourceFilePath == "":
			// must upload file as we have set a new source one
			if err := validateDestinationDriveExists(ctx, c, resolveNewDestinationFilePath); err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			err := c.RemoteFileUpload(ctx, newSourceFilePath, resolveNewDestinationFilePath)
			return resolveNewDestinationFilePath, true, err
		case d.HasChange(sourceFilePathHashKey):
			// must upload file over existing one as hash has changed
			if err := validateDestinationDriveExists(ctx, c, resolveNewDestinationFilePath); err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			err := c.RemoteFileUpload(ctx, newSourceFilePath, resolveNewDestinationFilePath)
			return resolveNewDestinationFilePath, true, err
		}
	case sourceFilePath != "" && d.HasChange(destinationFilePathKey):
		o, n := d.GetChange(destinationFilePathKey)
		oldDestinationFilePath := o.(string)
		newDestinationFilePath := n.(string)

		resolveOldDestinationFilePath := oldDestinationFilePath
		if resolveOldDestinationFilePath == "" {
			resolveOldDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
		}

		resolveNewDestinationFilePath := newDestinationFilePath
		if resolveNewDestinationFilePath == "" {
			resolveNewDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
		}

		if resolveOldDestinationFilePath != resolveNewDestinationFilePath {
			if err := validateDestinationDriveExists(ctx, c, resolveOldDestinationFilePath); err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			if err := validateDestinationDriveExists(ctx, c, resolveNewDestinationFilePath); err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			// must delete the old filename as we have renamed it and we are not sure if any other properties have changed
			err := c.RemoteFileDelete(ctx, resolveOldDestinationFilePath)
			if err != nil {
				return resolveNewDestinationFilePath, true, err
			}

			// must upload file as we deleted the old one and we are expecting a file
			err = c.RemoteFileUpload(ctx, sourceFilePath, resolveNewDestinationFilePath)
			return resolveNewDestinationFilePath, true, err
		}
	case sourceFilePath != "" && d.HasChange(sourceFilePathHashKey):
		// must upload file over existing one as hash has changed
		resolveDestinationFilePath := destinationFilePath
		if resolveDestinationFilePath == "" {
			resolveDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
		}

		// Validation occurs after resolveDestinationFilePath is computed. $env:* paths are
		// intentionally skipped by validateDestinationDriveExists.
		if err := validateDestinationDriveExists(ctx, c, resolveDestinationFilePath); err != nil {
			return resolveDestinationFilePath, true, err
		}

		err := c.RemoteFileUpload(ctx, sourceFilePath, resolveDestinationFilePath)
		return resolveDestinationFilePath, true, err
	case sourceFilePath != "":
		resolveDestinationFilePath := destinationFilePath
		if resolveDestinationFilePath == "" {
			resolveDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
		}

		if err := validateDestinationDriveExists(ctx, c, resolveDestinationFilePath); err != nil {
			return resolveDestinationFilePath, true, err
		}

		log.Printf("[INFO][iso-image][create] check if iso exists: %#v", resolveDestinationFilePath)
		resolveDestinationFilePathExists, err := c.RemoteFileExists(ctx, resolveDestinationFilePath)
		if err != nil {
			return resolveDestinationFilePath, true, fmt.Errorf("checking for existing %s: %+v", resolveDestinationFilePath, err)
		}

		if !resolveDestinationFilePathExists {
			// must upload file over as we are missing expected file
			err = c.RemoteFileUpload(ctx, sourceFilePath, resolveDestinationFilePath)
			return resolveDestinationFilePath, true, err
		}
	}

	resolveDestinationFilePath := destinationFilePath
	if resolveDestinationFilePath == "" {
		resolveDestinationFilePath = winPath(filepath.Join(`$env:TEMP`, filepath.Base(sourceFilePath)))
	}

	return resolveDestinationFilePath, false, nil
}

func resourceHyperVIsoImageUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var err error
	log.Printf("[INFO][iso-image][update] updating remote iso: %#v", d)
	c := meta.(api.Client)

	destinationIsoFilePath := d.Id()

	if destinationIsoFilePath != (d.Get("destination_iso_file_path")).(string) {
		return diag.FromErr(fmt.Errorf("cannot update destination_iso_file_path from %+v to %+v", destinationIsoFilePath, (d.Get("destination_iso_file_path")).(string)))
	}

	sourceIsoFilePath := (d.Get("source_iso_file_path")).(string)
	sourceIsoFilePathHash := (d.Get("source_iso_file_path_hash")).(string)
	sourceZipFilePath := (d.Get("source_zip_file_path")).(string)
	sourceZipFilePathHash := (d.Get("source_zip_file_path_hash")).(string)
	sourceBootFilePath := (d.Get("source_boot_file_path")).(string)
	sourceBootFilePathHash := (d.Get("source_boot_file_path_hash")).(string)
	destinationZipFilePath := (d.Get("destination_zip_file_path")).(string)
	destinationBootFilePath := (d.Get("destination_boot_file_path")).(string)
	media := api.ToIsoMediaType((d.Get("iso_media_type")).(string))
	fileSystem := api.ToIsoFileSystemType((d.Get("iso_file_system_type")).(string))
	volumeName := (d.Get("volume_name")).(string)

	resolveDestinationIsoFilePath, resolveDestinationIsoFilePathChanged, err := ensureFileStateUpdate(ctx, d, c, "iso")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_iso_file_path", resolveDestinationIsoFilePath); err != nil {
		return diag.FromErr(err)
	}

	resolveDestinationZipFilePath, resolveDestinationZipFilePathChanged, err := ensureFileStateUpdate(ctx, d, c, "zip")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_zip_file_path", resolveDestinationZipFilePath); err != nil {
		return diag.FromErr(err)
	}

	resolveDestinationBootFilePath, resolveDestinationBootFilePathChanged, err := ensureFileStateUpdate(ctx, d, c, "boot")
	if err != nil {
		return diag.FromErr(err)
	}
	if err := d.Set("resolve_destination_boot_file_path", resolveDestinationBootFilePath); err != nil {
		return diag.FromErr(err)
	}

	recreateDestinationIsoFilePath := false
	if !resolveDestinationIsoFilePathChanged && (resolveDestinationZipFilePathChanged || resolveDestinationBootFilePathChanged) || ((sourceZipFilePath != "" || sourceBootFilePath != "") && (d.HasChange("iso_media_type") || d.HasChange("iso_file_system_type") || d.HasChange("volume_name"))) {
		// must delete the iso file as we need to recreate it as the way it is created has changed
		err = c.RemoteFileDelete(ctx, resolveDestinationIsoFilePath)
		if err != nil {
			return diag.FromErr(err)
		}
		recreateDestinationIsoFilePath = true
	}

	if resolveDestinationIsoFilePathChanged || resolveDestinationZipFilePathChanged || resolveDestinationBootFilePathChanged || recreateDestinationIsoFilePath || d.HasChange("source_iso_file_path") || d.HasChange("source_iso_file_path_hash") || d.HasChange("source_zip_file_path") || d.HasChange("source_zip_file_path_hash") || d.HasChange("source_boot_file_path") || d.HasChange("source_boot_file_path_hash") || d.HasChange("destination_zip_file_path") || d.HasChange("destination_boot_file_path") {
		err = c.CreateOrUpdateIsoImage(ctx, sourceIsoFilePath, sourceIsoFilePathHash, sourceZipFilePath, sourceZipFilePathHash, sourceBootFilePath, sourceBootFilePathHash, destinationIsoFilePath, destinationZipFilePath, destinationBootFilePath, media, fileSystem, volumeName, resolveDestinationIsoFilePath, resolveDestinationZipFilePath, resolveDestinationBootFilePath)
		if err != nil {
			return diag.FromErr(err)
		}
	}

	log.Printf("[INFO][iso-image][update] updated remote iso: %#v", d)

	return resourceHyperVIsoImageRead(ctx, d, meta)
}

func resourceHyperVIsoImageDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	c := meta.(api.Client)

	if d.Get("keep_on_destroy").(bool) {
		log.Printf("[INFO][iso-image][delete] keep_on_destroy is true - preserving remote files")
		return nil
	}

	resolvedDestinationIsoFilePath := (d.Get("resolve_destination_iso_file_path")).(string)
	if resolvedDestinationIsoFilePath == "" {
		resolvedDestinationIsoFilePath = (d.Get("destination_iso_file_path")).(string)
	}

	resolvedDestinationZipFilePath := (d.Get("resolve_destination_zip_file_path")).(string)
	if resolvedDestinationZipFilePath == "" {
		resolvedDestinationZipFilePath = (d.Get("destination_zip_file_path")).(string)
	}

	resolvedDestinationBootFilePath := (d.Get("resolve_destination_boot_file_path")).(string)
	if resolvedDestinationBootFilePath == "" {
		resolvedDestinationBootFilePath = (d.Get("destination_boot_file_path")).(string)
	}

	if resolvedDestinationIsoFilePath != "" {
		log.Printf("[INFO][iso-image][delete] deleting remote iso file: %s", resolvedDestinationIsoFilePath)
		err := c.RemoteFileDelete(ctx, resolvedDestinationIsoFilePath)
		if err != nil {
			return diag.FromErr(err)
		}
		log.Printf("[INFO][iso-image][delete] deleted remote iso file: %s", resolvedDestinationIsoFilePath)
		// NOTE: No longer deleting separate metadata file - state-only approach
	}

	if resolvedDestinationZipFilePath != "" {
		log.Printf("[INFO][iso-image][delete] deleting remote zip file: %s", resolvedDestinationZipFilePath)
		err := c.RemoteFileDelete(ctx, resolvedDestinationZipFilePath)
		if err != nil {
			return diag.FromErr(err)
		}
		log.Printf("[INFO][iso-image][delete] deleted remote zip file: %s", resolvedDestinationZipFilePath)
	}

	if resolvedDestinationBootFilePath != "" {
		log.Printf("[INFO][iso-image][delete] deleting remote boot file: %s", resolvedDestinationBootFilePath)
		err := c.RemoteFileDelete(ctx, resolvedDestinationBootFilePath)
		if err != nil {
			return diag.FromErr(err)
		}
		log.Printf("[INFO][iso-image][delete] deleted remote boot file: %#v", d)
	}

	return nil
}
